modLoader = "javafml"
loaderVersion = "[39,)"
issueTrackerURL = "https://github.com/Surreality-Modding/${repo}/issues"
license = "GPLv3"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Surreality Modding"
credits = "Haunted Chest, StevenPlayzz, TheOnlyTails"
description = '''
A new dimension based around new exotic plants, new features and mobs, and an entire new dimension to explore!
'''
#updateJSONURL = ""
logoFile="logo.png"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "pollen"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "BEFORE"
side = "BOTH"